# Use new trusty images, should yield newer compilers and packages
# ref: https://github.com/genbattle/dkm.git
sudo: required
dist: precise
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++4.8
      - clang
script:
  - make init
  - make
  - make test
